version: '3'
services:
  jaeger:
    image: 'jaegertracing/all-in-one:latest'
    ports:
      - '6831:6831/udp'
      - '16686:16686'
      - '5775:5775/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '14268:14268'
      - '14250:14250'
      - '9411:9411'
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_PORT=14268
    networks:
      - app_network

  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/var/lib/rabbitmq'
      - 'rabbitmq_log:/var/log/rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=auuntoo
      - RABBITMQ_DEFAULT_PASS=auuntoo
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
    restart: always
    depends_on:
      - jaeger
      - postgres
      - redis 
      - mongo
    networks:
      - app_network

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=auuntoo
      - POSTGRES_PASSWORD=auuntoo
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    depends_on:
      - jaeger
    networks:
      - app_network
      
  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    depends_on:
      - jaeger
    networks:
      - app_network
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: auuntoo
      MONGO_INITDB_ROOT_PASSWORD: auuntoo
    ports:
      - '27017:27017'
    volumes:
      - ./workspace:/workspace
      - type: volume
        source: mongodb_data_volume
        target: /data/db
    depends_on:
      - jaeger
    networks:
      - app_network
      
  service_a:
    build:
      context: ./service-a
    ports:
      - 5001:5001
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app_network

  service_b:
    build:
      context: ./service-b
    ports:
      - 5002:5002
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  rabbitmq_data:
    driver: local
  rabbitmq_log:
    driver: local
  db:
    driver: local
  mongodb_data_volume:
    driver: local